### ISSUE TITLE
省份选择重庆市，城市选择除了市辖区还有其他县

### ISSUE THREAD

**Issue by leleccccc** [oyv1cent/iview-area-new#2]
省份选择重庆市，城市选择除了市辖区还有其他县

**Comment by oyv1cent** [comment]
@leleccccc 这个数据是从[area-data](https://github.com/dwqs/area-data)那边获取的，所以数据不全也没办法（这已经是当初所能找到最合适的数据源了，但他现在也一年多没更新了）

如果有找到更合适的数据源，可以考虑fork一下然后替换掉现在的数据源
